# Default values for pubobot2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/kaszpir/pubobot2
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "formatting"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config: |-
  # Your discord credentials
  DC_BOT_TOKEN = ""
  # DC_CLIENT_ID = 1234567890
  # DC_CLIENT_SECRET = ""
  # DC_INVITE_LINK = ""
  DC_OWNER_ID = 1234567890  # your user id (owner of the bot)

  DB_URI = "mysql://pubobot:pubobot-password@bot1-sql-mariadb:3306/pubobot" # mysql://user:password@hostname:port/database"
  LOG_LEVEL = "CHAT" # CHAT, DEBUG, COMMANDS, INFO or ERRORS
  COMMANDS_URL = "https://github.com/Leshaka/PUBobot2/blob/main/COMMANDS.md#avaible-commands"
  HELP = """PUBobot2 is a discord bot for pickup games organisation.
  Commands: <https://github.com/Leshaka/PUBobot2/blob/main/COMMANDS.md>.
  If you need help with the bot feel free to join PUBobot-dev guild: <https://discord.gg/rjNt9nC>.
  """
  STATUS = "" # bot presence url, string

  # Web server, requires python module which is not in github repo
  WS_ENABLE = False
  WS_HOST = "0.0.0.0"
  WS_PORT = 5000
  WS_OAUTH_REDIRECT_URL = ""
  WS_ROOT_URL = ""
  WS_SSL_CERT_FILE = ""
  WS_SSL_KEY_FILE = ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1001

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001

service:
  enabled: false
  type: ClusterIP
  port: 5000
  containerPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


persistence:
  enabled: false
  # existingClaim: derp
  # accessModes: 0644
  size: 10Gi
  # storageClass: ~
